blueprint:
  name: Power-dependant state notification
  description: Send a notification based on the power level of a device
  domain: automation
  source_url: https://github.com/tlanfer/ha-blueprints/blob/main/power-alarm.yaml
  author: tlanfer

  input:
    power_entity:
      name: Power sensor
      selector:
        entity:
          filter:
            device_class: power
            domain: sensor

mode: restart

trigger:
  platform: numeric_state
  entity_id: !input power_entity
  above: 1000

action:
  - alias: "Finish stuff"
    stop: "We are done here"