blueprint:
  name: Power-dependant state notification
  description: Send a notification based on the power level of a device
  domain: automation
  source_url: https://github.com/tlanfer/ha-blueprints/blob/main/power-notifications.yaml
  author: tlanfer

  input:
    power_entity:
      name: Power sensor
      selector:
        entity:
          filter:
            device_class: power
            domain: sensor

    power_level:
      name: Power threshold
      description: At what threshold should the device be considered powered on
      default: 10
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: watt

    power_on_duration:
      name: Power on duration
      description: How long to be above the threshold
      default: 5
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    power_off_duration:
      name: Power off duration
      description: How long to be below the threshold
      default: 5
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    notification_template:
      name: Notification
      description: The notification to be sent after turning off. Allows templating.
      selector:
        text:
          multiline: true

mode: restart

trigger:
  platform: numeric_state
  entity_id: !input power_entity
  above: 1000

action:
  - alias: "Finish stuff"
    stop: "We are done here"